version: "3.8"
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meu_banco
    volumes:
      - db-data:/var/lib/postgresql/data

  landing:
    build: ./landing-page
    ports:
      - "8080:80"

volumes:
  db-data:
